
skillMetadata:
  sections:
    - name: Music source
      fields:
        - name: musicsource
          type: text
          label: Directory where the music files are located
          value: "~/music"
        
